[project]
name = "atividades"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mininet>=2.3.0.dev6",
]

[project.scripts]
item_01 = "item_01.main:run_topology"
